# Generated by Django 6.0 on 2026-01-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(max_length=50)),
                ('Doctor_designation', models.CharField(max_length=50)),
                ('Doctor_email', models.CharField(max_length=50, unique=True)),
                ('Doctor_phone_number', models.CharField(max_length=11)),
                ('Doctor_salary', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
