# Generated by Django 6.0 on 2026-01-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalnurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nurse_name', models.CharField(max_length=50)),
                ('Nurse_designation', models.CharField(max_length=50)),
                ('Nurse_email', models.CharField(max_length=50, unique=True)),
                ('Nurse_phone_number', models.CharField(max_length=11)),
                ('Nurse_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
