# Generated by Django 6.0 on 2026-01-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_name', models.CharField(max_length=50)),
                ('Employee_designation', models.CharField(max_length=50)),
                ('Employee_email', models.CharField(max_length=50, unique=True)),
                ('Employee_phone_number', models.CharField(help_text='Enter Bangladesi mobile number:', max_length=11)),
                ('Employee_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
